[package]
name = "jos"
version = "1.0.0"
authors = ["Dong Zhou"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
spin = "0.3.4"

[dependencies.x86]
git = "https://github.com/gz/rust-x86.git"
